CREATE TABLE AUCTION_ITEM (
    ID INT IDENTITY(200,1) PRIMARY KEY,
    NAME NVARCHAR(255),
    IS_ACTIVE BIT,
    PICTURE NVARCHAR(255),
    CREATED_BY INT,
    CREATED_DATE DATETIME,
    MODIFIED_BY INT,
    MODIFIED_DATE DATETIME
);
