CREATE TABLE DRAFT_SESSION_DETAIL (
    ID INT IDENTITY(200,1) PRIMARY KEY,
    TEAM_ID INT,
    AUCTION_ITEM_ID INT,
    IS_ACTIVE BIT,
    CREATED_BY INT,
    CREATED_DATE DATETIME,
    MODIFIED_BY INT,
    MODIFIED_DATE DATETIME
);
