DROP TABLE DRAFT_SESSION_DETAIL;

CREATE TABLE DRAFT_SESSION_DETAIL (
    ID INT IDENTITY(200,1) PRIMARY KEY,
    TEAM_ID INT,
    CREATED_BY INT,
    CREATED_DATE DATETIME,
    MODIFIED_BY INT,
    MODIFIED_DATE DATETIME
);
