CREATE TABLE DRAFT_SESSION (
    ID INT IDENTITY(200,1) PRIMARY KEY,
    NAME NVARCHAR(255),
    IS_ACTIVE BIT,
    PICK_TIME TIME,
    BUDGET INT,
    /*PICK_STYLE INT,*/
    CREATED_BY INT,
    CREATED_DATE DATETIME,
    MODIFIED_BY INT,
    MODIFIED_DATE DATETIME
);
