DROP TABLE DRAFT_SESSION;

CREATE TABLE DRAFT_SESSION (
    ID INT IDENTITY(200,1) PRIMARY KEY,
    NAME NVARCHAR(255),
    IS_ACTIVE BIT,
    PICK_TIME TIME,
    BUDGET INT,
    PICK_STYLE_ID INT,
    CREATED_BY INT,
    CREATED_DATE DATETIME,
    MODIFIED_BY INT,
    MODIFIED_DATE DATETIME
);

ALTER TABLE DRAFT_SESSION
ADD CONSTRAINT FK_DRAFTSESSION_PICKSTYLE
FOREIGN KEY (PICK_STYLE_ID) REFERENCES PICK_STYLE(ID);
