DROP TABLE TEAM;

CREATE TABLE TEAM (
    ID INT IDENTITY(200,1) PRIMARY KEY,
    NAME NVARCHAR(255),
    IS_ACTIVE BIT,
    CREATED_BY INT,
    BUDGET INT,
    CREATED_DATE DATETIME,
    MODIFIED_BY INT,
    MODIFIED_DATE DATETIME
);
