CREATE TABLE TEAM_AUCTION_ITEM (
    ID INT IDENTITY(200,1) PRIMARY KEY,
    TEAM_ID INT,
    AUCTION_ITEM_ID INT,
    IS_ACTIVE BIT,
    CREATED_BY INT,
    CREATED_DATE DATETIME,
    MODIFIED_BY INT,
    MODIFIED_DATE DATETIME
);

ALTER TABLE TEAM_AUCTION_ITEM
ADD CONSTRAINT FK_TEAM_AUCTION_TEAM
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID);

ALTER TABLE TEAM_AUCTION_ITEM
ADD CONSTRAINT FK_TEAM_AUCTION_AUCTION_ITEM
FOREIGN KEY (AUCTION_ITEM_ID) REFERENCES AUCTION_ITEM(ID);